from datetime import datetime
from enum import Enum
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field

class WorkflowStatus(str, Enum):
    """Execution status for a Workflow Run."""
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    BLOCKED_ON_APPROVAL = "blocked_on_approval"

class StepStatus(str, Enum):
    """Execution status for an individual step in a workflow."""
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"

class WorkflowStep(BaseModel):
    """Represents a discrete step inside an execution workflow."""
    id: str = Field(..., description="Unique step ID, e.g., 'telemetry_collection'")
    name: str = Field(..., description="Human-readable name of the step")
    status: StepStatus = Field(default=StepStatus.PENDING)
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    error_message: Optional[str] = None
    retries_attempted: int = Field(default=0, description="Count of execution retries run for this step")

class ActionPlan(BaseModel):
    """Contains targeted actions generated by agents for execution."""
    id: str = Field(..., description="Action UUID")
    recommendation_id: str = Field(..., description="Link to DB recommendation")
    action_type: str = Field(..., description="Type of action (stop/resize/delete)")
    resource_id: str = Field(..., description="Target cloud resource path")
    risk_level: str = Field(..., description="Risk category (low/high)")
    approval_required: bool = Field(..., description="Flag if human approval is required before running")

class ExecutionResult(BaseModel):
    """Result payload produced after running an ActionPlan item."""
    action_id: str = Field(..., description="Link to ActionPlan item")
    success: bool = Field(..., description="True if action executed successfully")
    error_message: Optional[str] = None
    executed_at: datetime = Field(default_factory=datetime.utcnow)
    rollback_executed: bool = Field(default=False, description="Flag if recovery rollback was triggered")
    rollback_success: bool = Field(default=False, description="True if rollback was completed successfully")

class ApprovalRequest(BaseModel):
    """Approval item generated for high-risk actions requiring sign-off."""
    id: str = Field(..., description="Unique approval task ID")
    recommendation_id: str = Field(..., description="Link to target recommendation")
    resource_id: str = Field(..., description="Target cloud resource path")
    action_type: str = Field(..., description="Target execution action")
    token: Optional[str] = Field(default=None, description="Cryptographic security verification token")
    status: str = Field(default="pending", description="Task status (pending/approved/rejected)")
    created_at: datetime = Field(default_factory=datetime.utcnow)

class WorkflowRun(BaseModel):
    """Represents the complete execution context and state of an optimization sweep."""
    id: str = Field(..., description="Workflow Run execution UUID")
    run_id: str = Field(..., description="Linked DB Run ID")
    status: WorkflowStatus = Field(default=WorkflowStatus.PENDING)
    steps: List[WorkflowStep] = Field(default_factory=list)
    action_plan: Optional[ActionPlan] = None
    execution_result: Optional[ExecutionResult] = None
    approval_request: Optional[ApprovalRequest] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
