import React, { useState } from "react";
import { 
  Sparkles,
  HelpCircle,
  Cpu,
  Shield,
  Award,
  DollarSign,
  ChevronRight,
  X,
  FileText
} from "lucide-react";
import type { RecommendationDTO } from "../api/client";

interface RecommendationsProps {
  recommendations: RecommendationDTO[];
}

export function Recommendations({ recommendations }: RecommendationsProps) {
  const [selectedReco, setSelectedReco] = useState<RecommendationDTO | null>(null);
  const [isDrawerOpen, setIsDrawerOpen] = useState(false);

  const handleInspect = (reco: RecommendationDTO) => {
    setSelectedReco(reco);
    setIsDrawerOpen(true);
  };

  // Generate a detailed trace based on recommendation properties
  const generateTrace = (reco: RecommendationDTO) => {
    const isVm = reco.resource_id.toLowerCase().includes("vm");
    
    // Check if real reasoning chain exists, otherwise use fallback mock trace
    if (reco.reasoning_chain) {
      const chain = reco.reasoning_chain;
      return {
        agentGroup: isVm ? "Compute Governance Cluster" : "Storage Purging Group",
        telemetryEvaluated: reco.evidence || `Metric underutilization identified.`,
        policyTrigger: chain.policy?.compliant === false
          ? `Policy Alert: Protected resource check failed. Action blocked.`
          : `Policy ID: POL-${isVm ? "VM" : "DISK"}-098 checked. ${chain.policy?.requires_approval ? "Requires manual approval signature." : "Eligible for auto-execution."}`,
        decisionPath: [
          {
            agent: "Telemetry Agent",
            action: "Collected live resource metrics from Azure Resource Manager and Azure Monitor.",
            confidence: 1.0,
            timestamp: "Phase 1: Telemetry"
          },
          {
            agent: "Analysis Agent",
            action: `Analyzed telemetry against thresholds. Finding: ${chain.analysis?.decision || "Idle resource identified"}.`,
            confidence: chain.analysis?.confidence || 0.95,
            timestamp: "Phase 2: Analysis"
          },
          {
            agent: "FinOps Agent",
            action: `Estimated cost impact. Monthly savings: $${chain.finops?.estimated_monthly_savings?.toFixed(2)} under action '${reco.action_type}'.`,
            confidence: 0.90,
            timestamp: "Phase 3: FinOps"
          },
          {
            agent: "Policy Agent",
            action: `Checked governance rules. Compliant: ${chain.policy?.compliant ? "YES" : "NO"}, Requires Approval: ${chain.policy?.requires_approval ? "YES" : "NO"}.`,
            confidence: 0.98,
            timestamp: "Phase 4: Policy"
          },
          {
            agent: "Decision Agent",
            action: `Finalized recommendation path. Action: ${chain.decision?.final_action || reco.action_type}, Approved: ${chain.decision?.approved ? "YES" : "NO (Awaiting Gate)"}.`,
            confidence: reco.confidence_score || chain.decision?.confidence || 0.95,
            timestamp: "Phase 5: Decision"
          }
        ]
      };
    }

    return {
      agentGroup: isVm ? "Compute Governance Cluster" : "Storage Purging Group",
      telemetryEvaluated: isVm 
        ? "Avg CPU Util: 1.8%, Network In: 2.1KB/s, Memory Usage: 12%" 
        : "Disk Unattached: Since 2026-06-10T14:00:00Z, Size: 128 GB",
      policyTrigger: isVm
        ? "Policy ID: POL-VM-098 (Idle virtual machines trigger remediation stop if CPU < 5.0% for 7 days)"
        : "Policy ID: POL-DISK-002 (Unattached disk purge, eligible for deletion if unattached for > 3 days)",
      decisionPath: [
        {
          agent: "Telemetry Agent",
          action: "Evaluated metrics against Azure Monitor historical logs.",
          confidence: 0.98,
          timestamp: "Phase 1: Sweep"
        },
        {
          agent: "Decision Agent",
          action: `Proposed action '${reco.action_type}' with saving projection $${reco.saving_amount.toFixed(2)}.`,
          confidence: 0.94,
          timestamp: "Phase 2: Evaluate"
        },
        {
          agent: "Audit Agent",
          action: `Cross-referenced policy guidelines. Risk classified as ${reco.risk_level.toUpperCase()}. Gating manual approval.`,
          confidence: 0.97,
          timestamp: "Phase 3: Audit"
        }
      ]
    };
  };

  const trace = selectedReco ? generateTrace(selectedReco) : null;

  return (
    <div className="space-y-8 animate-fadeIn relative">
      {/* Header Widget */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-[#22252d] pb-6">
        <div>
          <h2 className="text-xl font-extrabold text-white tracking-wide">AI RECOMMENDATIONS</h2>
          <p className="text-xs text-slate-400 mt-1">Autonomous cost reduction and right-sizing proposals generated by agent collaboration reasoning loops.</p>
        </div>
        <div className="flex items-center gap-2 text-[10px] text-slate-400 font-mono">
          <span className="h-2 w-2 rounded-full bg-indigo-500 animate-pulse" />
          <span>PROPOSALS REGISTRY</span>
        </div>
      </div>

      {/* Main Table Card */}
      <div className="p-6 bg-[#111318] border border-[#22252d] rounded-xl shadow-lg">
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse text-xs">
            <thead>
              <tr className="border-b border-[#22252d] text-slate-400 uppercase font-bold text-[10px] tracking-wider">
                <th className="py-3 px-4">Resource ID</th>
                <th className="py-3 px-4">Action</th>
                <th className="py-3 px-4">Rationale Rationale</th>
                <th className="py-3 px-4">Risk Profile</th>
                <th className="py-3 px-4">Agent Confidence</th>
                <th className="py-3 px-4">Savings Amount</th>
                <th className="py-3 px-4">Status</th>
                <th className="py-3 px-4 text-center">Explainability</th>
              </tr>
            </thead>
            <tbody>
              {recommendations.length === 0 ? (
                <tr>
                  <td colSpan={8} className="py-12 text-center text-slate-500 italic">
                    No recommendations currently populated in registry database.
                  </td>
                </tr>
              ) : (
                recommendations.map((reco) => (
                  <tr key={reco.id} className="border-b border-[#1c1e24] hover:bg-[#16191f]/50 transition-all duration-150">
                    <td className="py-3.5 px-4 font-mono font-bold text-white">{reco.resource_id}</td>
                    <td className="py-3.5 px-4">
                      <span className={`px-2 py-0.5 rounded text-[9px] font-extrabold uppercase font-mono border ${
                        reco.action_type === "stop"
                          ? "bg-rose-500/10 text-rose-400 border-rose-500/25"
                          : reco.action_type === "resize"
                            ? "bg-amber-500/10 text-amber-400 border-amber-500/25"
                            : "bg-cyan-500/10 text-cyan-400 border-cyan-500/25"
                      }`}>
                        {reco.action_type}
                      </span>
                    </td>
                    <td className="py-3.5 px-4 text-slate-400 max-w-[280px] truncate" title={reco.rationale}>
                      {reco.rationale}
                    </td>
                    <td className="py-3.5 px-4">
                      <span className={`px-2 py-0.5 rounded text-[9px] uppercase font-bold ${
                        reco.risk_level === "high" 
                          ? "bg-rose-500/10 text-rose-500 border border-rose-500/20" 
                          : "bg-cyan-500/10 text-cyan-400 border border-cyan-400/20"
                      }`}>
                        {reco.risk_level}
                      </span>
                    </td>
                    <td className="py-3.5 px-4 font-bold font-mono text-indigo-400">
                      {reco.confidence_score !== undefined && reco.confidence_score !== null
                        ? `${(reco.confidence_score * 100).toFixed(0)}%`
                        : "95%"}
                    </td>
                    <td className="py-3.5 px-4 text-emerald-400 font-extrabold font-mono">${reco.saving_amount.toFixed(2)}</td>
                    <td className="py-3.5 px-4">
                      <span className={`inline-flex items-center gap-1.5 px-2 py-0.5 rounded text-[9px] font-extrabold uppercase font-mono ${
                        reco.status === "executed"
                          ? "bg-emerald-500/10 text-emerald-400 border border-emerald-500/20"
                          : reco.status === "pending"
                            ? "bg-amber-500/10 text-amber-400 border border-amber-500/20 animate-pulse"
                            : reco.status === "approved"
                              ? "bg-indigo-500/10 text-indigo-400 border border-indigo-500/20"
                              : "bg-rose-500/10 text-rose-400 border border-rose-500/20"
                      }`}>
                        <circle cx="2" cy="2" r="2" fill={
                          reco.status === "executed" ? "#10b981" : reco.status === "pending" ? "#f59e0b" : "#6366f1"
                        } />
                        {reco.status}
                      </span>
                    </td>
                    <td className="py-3.5 px-4 text-center">
                      <button
                        onClick={() => handleInspect(reco)}
                        className="px-2.5 py-1 rounded bg-[#181b21] hover:bg-indigo-500 text-slate-400 hover:text-white border border-[#22252d] text-[10px] font-bold uppercase transition-all flex items-center gap-1 mx-auto"
                      >
                        <span>Explain</span>
                        <ChevronRight className="h-3 w-3" />
                      </button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Slide-out Drawer Container */}
      {isDrawerOpen && selectedReco && trace && (
        <div className="fixed inset-0 z-50 flex justify-end bg-black/60 backdrop-blur-sm animate-fadeIn">
          {/* Dismiss Backpane */}
          <div className="flex-1" onClick={() => setIsDrawerOpen(false)} />

          {/* Drawer Element */}
          <div className="w-full max-w-2xl bg-[#111318] border-l border-[#22252d] h-full shadow-2xl overflow-y-auto p-8 space-y-6 flex flex-col justify-between animate-slideLeft">
            
            {/* Header */}
            <div className="flex items-center justify-between border-b border-[#22252d] pb-4">
              <div className="flex items-center gap-2">
                <Sparkles className="h-5 w-5 text-indigo-400" />
                <h3 className="font-heading font-extrabold text-sm uppercase text-white tracking-wide">Explainability Trace</h3>
              </div>
              <button 
                onClick={() => setIsDrawerOpen(false)}
                className="p-1 rounded bg-[#181b21] border border-[#22252d] hover:bg-[#1c1e24] text-slate-400"
              >
                <X className="h-4 w-4" />
              </button>
            </div>

            {/* Context Summary Cards */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="p-4 bg-[#090b0f] border border-[#22252d] rounded-lg">
                <div className="flex items-center gap-2 text-[9px] text-slate-500 mb-1 font-bold uppercase tracking-wider">
                  <Cpu className="h-3.5 w-3.5 text-indigo-400" />
                  <span>Agent Telemetry Input</span>
                </div>
                <p className="text-xs font-bold text-white mt-1 leading-normal">{trace.telemetryEvaluated}</p>
              </div>
              
              <div className="p-4 bg-[#090b0f] border border-[#22252d] rounded-lg">
                <div className="flex items-center gap-2 text-[9px] text-slate-500 mb-1 font-bold uppercase tracking-wider">
                  <Shield className="h-3.5 w-3.5 text-amber-500" />
                  <span>Governance Limits Checker</span>
                </div>
                <p className="text-[10px] font-mono font-bold text-slate-300 leading-relaxed mt-1">{trace.policyTrigger}</p>
              </div>
            </div>

            {/* Decision Path Map */}
            <div className="space-y-4">
              <h4 className="text-xs font-bold uppercase tracking-wider text-slate-200">Remediation Decision Path</h4>
              <div className="space-y-4 relative before:absolute before:left-5 before:top-2 before:bottom-2 before:w-0.5 before:bg-[#22252d]">
                {trace.decisionPath.map((step, idx) => (
                  <div key={idx} className="flex gap-4 items-start relative pl-1">
                    <div className="h-8.5 w-8.5 rounded-full bg-[#16191f] border border-[#22252d] flex items-center justify-center font-bold text-xs text-indigo-400 shrink-0 z-10 font-mono">
                      {idx + 1}
                    </div>
                    <div className="flex-1 bg-[#090b0f]/50 p-4 border border-[#22252d] rounded-lg space-y-1.5 hover:border-indigo-500/20 transition-all duration-200">
                      <div className="flex items-center justify-between">
                        <span className="text-xs font-extrabold text-white font-mono uppercase tracking-wide">
                          {step.agent}
                        </span>
                        <span className="text-[9px] text-slate-500 font-mono uppercase tracking-wider">{step.timestamp}</span>
                      </div>
                      <p className="text-xs text-slate-400 leading-normal">{step.action}</p>
                      <div className="pt-1 flex items-center gap-1.5 text-[9px] text-indigo-400 font-mono font-bold">
                        <Award className="h-3 w-3" />
                        <span>CONFIDENCE SCORE: {(step.confidence * 100).toFixed(0)}%</span>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Raw JSON Trace Inspector */}
            <div className="space-y-2">
              <div className="flex items-center gap-1.5 text-xs font-bold uppercase tracking-wider text-slate-200">
                <FileText className="h-4 w-4 text-indigo-400" />
                <span>Raw Response Metadata</span>
              </div>
              <div className="bg-[#090b0f] p-4 rounded-lg font-mono text-[10px] text-emerald-400 border border-[#22252d] max-h-44 overflow-y-auto">
                <pre className="overflow-x-auto">{JSON.stringify(selectedReco, null, 2)}</pre>
              </div>
            </div>

            {/* Footer Close */}
            <div className="pt-4 border-t border-[#22252d] flex justify-end">
              <button 
                onClick={() => setIsDrawerOpen(false)}
                className="px-4 py-2 rounded bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold uppercase transition-all"
              >
                Done Inspecting
              </button>
            </div>

          </div>
        </div>
      )}
    </div>
  );
}
